CREATE PROCEDURE INSERTAR_REQUI_INTERNA

@PRIORIDAD VARCHAR(13),
@MODALIDAD VARCHAR(10),
@TEMA VARCHAR (50),
@FECHA DATE,
@HORA_INICIO TIME,
@DURACION VARCHAR(4),
@NUMERO_PARTICIPANTES VARCHAR(3),
@LUGAR VARCHAR(50),
@SALA VARCHAR(20),
@ACOMODO VARCHAR (12),
@POLITICAS VARCHAR(2),
@PARTICIPANTES VARCHAR(10),
@MATERIAL VARCHAR(2),
@COFFE VARCHAR(2),
@EVALUACION VARCHAR(2)

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRAN INSERTAR_REQUI_INTERNA
	BEGIN TRY
		INSERT INTO REQUI_INTERNA(
				PRIORIDAD,
				MODALIDAD,
				TEMA,
				FECHA,
				HORA_INICIO,
				DURACION_HORAS,
				NUMERO_PARTICIPANTES,
				LUGAR,
				ID_ESTADO_OFICINA,
				SALA, 
				ACOMODO,
				POLITICAS,
				PARTICIPANTES,
				MATERIAL_EXTRA,
				COFFE_BREAK,
				EVALUACION) 
		VALUES (
				@PRIORIDAD, 
				@MODALIDAD,
				@TEMA,
				@FECHA,
				@HORA_INICIO,
				@DURACION,
				@NUMERO_PARTICIPANTES,
				@LUGAR,
				NULL,
				@SALA,
				@ACOMODO,
				@POLITICAS,
				@PARTICIPANTES,
				@MATERIAL, 
				@COFFE,
				@EVALUACION);
		COMMIT TRAN INSERTAR_REQUI_INTERNA
	End Try
	Begin Catch
			Rollback INSERTAR_REQUI_INTERNA
	End Catch
END
GO