CREATE TABLE REQUI_AUDITORIA (
ID INT NOT NULL, 
ESTADO_OFICINA_ID INT NOT NULL, 
MES VARCHAR(20) NOT NULL, 
DESCRIPCION TEXT NOT NULL
)

CREATE TABLE ESTADO_OFICINA(
ID INT PRIMARY KEY NOT NULL,
ALAMO BIT NOT NULL,
APIZACO BIT NOT NULL,
CATEMACO BIT NOT NULL,
COATZACOALCOS BIT NOT NULL,
CORDOBA BIT NOT NULL,
FORTIN BIT NOT NULL,
HUAMANTLA BIT NOT NULL,
JUAN_PABLO BIT NOT NULL,
MARTINEZ BIT NOT NULL,
ORIZABA BIT NOT NULL,
POZA_RICA BIT NOT NULL,
PUEBLA_SUR BIT NOT NULL,
TEJERIA BIT NOT NULL,
TEZIUTLAN BIT NOT NULL,
TLAXCALA BIT NOT NULL,
TUXPAN BIT NOT NULL,
VERACRUZ BIT NOT NULL,
XALAPA BIT NOT NULL,
ZACATELCO BIT NOT NULL
)
ALTER TABLE EJEMPLO1(
ID INT NOT NULL PRIMARY KEY,
CAMPO1 VARCHAR NOT NULL,
CAMPO2 VARCHAR NOT NULL,
CAMPO3 VARCHAR NOT NULL
)

INSERT INTO EJEMPLO1 VALUES(3, '2', '2','2')

SELECT * FROM EJEMPLO1

SELECT * FROM  ESTADO_OFICINA

SELECT * FROM REQUI_AUDITORIA

SELECT * FROM REQUI_AUDITORIA, ESTADO_OFICINA WHERE ESTADO_OFICINA.ID = REQUI_AUDITORIA.ESTADO_OFICINA_ID

