CREATE PROCEDURE INSERTAR_REQUI_EXTERNA_OFICINAS
--DECLARAMOS LAS VARIABLES ESCALARES
--TABLA REQUI_INTERNA
@PRIORIDAD VARCHAR(13),
@MODALIDAD VARCHAR(10),
@TEMA VARCHAR (50),
@FECHA DATE,
@HORA_INICIO TIME,
@DURACION VARCHAR(4),
@NUMERO_PARTICIPANTES VARCHAR(3),
@LUGAR VARCHAR(50),
@SALA VARCHAR(20),
@ACOMODO VARCHAR (12),
@POLITICAS VARCHAR(2),
@PARTICIPANTES VARCHAR(10),
@MATERIAL VARCHAR(2),
@COFFE VARCHAR(2),
@EVALUACION VARCHAR(2),
--VARIABLES DE LA TABLA OFICINAS
@ALAMO BIT ,
@APIZACO BIT ,
@CATEMACO BIT ,
@COATZACOALCOS BIT ,
@CORDOBA BIT ,
@FORTIN BIT ,
@HUAMANTLA BIT ,
@JUAN_PABLO BIT ,
@MARTINEZ BIT ,
@ORIZABA BIT ,
@POZA_RICA BIT ,
@PUEBLA_SUR BIT ,
@TEJERIA BIT ,
@TEZIUTLAN BIT ,
@TLAXCALA BIT ,
@TUXPAN BIT ,
@VERACRUZ BIT ,
@XALAPA BIT ,
@ZACATELCO BIT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRAN INSERTAR_DATOS_REQUI_INTERNA
	BEGIN TRY
		INSERT INTO [dbo].[ESTADO_OFICINA] (ALAMO, APIZACO, CATEMACO, COATZACOALCOS, CORDOBA, FORTIN, HUAMANTLA, JUAN_PABLO, MARTINEZ, ORIZABA, POZA_RICA, PUEBLA_SUR, TEJERIA, TEZIUTLAN, TLAXCALA, TUXPAN , VERACRUZ, XALAPA, ZACATELCO) 
		VALUES (@ALAMO, @APIZACO, @CATEMACO, @COATZACOALCOS, @CORDOBA, @FORTIN, @HUAMANTLA, @JUAN_PABLO, @MARTINEZ, @ORIZABA, @POZA_RICA, @PUEBLA_SUR, @TEJERIA, @TEZIUTLAN, @TLAXCALA, @TUXPAN , @VERACRUZ, @XALAPA, @ZACATELCO);
		
		INSERT INTO [dbo].[REQUI_INTERNA] (PRIORIDAD, MODALIDAD,  TEMA, FECHA, HORA_INICIO, DURACION_HORAS, NUMERO_PARTICIPANTES, LUGAR,ID_ESTADO_OFICINA, SALA, ACOMODO, POLITICAS, PARTICIPANTES, MATERIAL_EXTRA, COFFE_BREAK, EVALUACION) 
		VALUES (@PRIORIDAD, @MODALIDAD,  @TEMA, @FECHA, @HORA_INICIO, @DURACION, @NUMERO_PARTICIPANTES, @LUGAR, @SALA,SCOPE_IDENTITY(), @ACOMODO, @POLITICAS, @PARTICIPANTES, @MATERIAL, @COFFE, @EVALUACION);

		COMMIT TRAN INSERTAR_DATOS_REQUI_INTERNA
	END TRY
	BEGIN CATCH
		ROLLBACK INSERTAR_DATOS_REQUI_INTERNA
	END CATCH
END
GO